### PR TITLE
Tempel-CLI Update

### PR DESCRIPTION
**Pull request by nsiregar**
Update tempel-cli-py for additional modules
1. argparse - for parsing argument
2. pyperclip - for clipboard usage

pyperclip module included

### CODE REVIEW

**Comment by herpiko** [comment]
@nsiregar  Emm, please keep the filename stay as `tempel`, without extension.

**Comment by nsiregar** [comment]
done rename `tempel.py` to `tempel`. sorry just habit using file extensions.

**Comment by herpiko** [comment]
@tuanpembual @nsiregar LGTM

[LGTM](https://lgtm.in/i/8oGpPS9Rp)

[:+1:](https://lgtm.in/u/8oGpPS9Rp) [:-1:](https://lgtm.in/r/8oGpPS9Rp)

**Comment by tuanpembual** [comment]
@nsiregar  can you please add comment each step?
just like old script. :)
It will help new contributor.

And @herpiko what should lang we use for help;etc (in code)?
It must consistent, Bahasa or English.

I prefer using Bahasa.

**Comment by herpiko** [comment]
@tuanpembual English.

If @nsiregar could make a promise to write docs in the next PR, lets this to be merged.

**Comment by nsiregar** [comment]
i've updated some docstrings in tempel

**Pull request merged**
