### PR TITLE
change -f to -s for stdin stream input

### PR DESCRIPTION
**Pull request by nsiregar**
change arg -f from file to -s from stream which read from stdin.
make possible to run `$ lsusb | tempel -s` also possible to stream file `$ tempel -s somefile.txt`

### CODE REVIEW

**Comment by herpiko** [comment]
@LGTM, but...

**Comment by herpiko** [comment]
@nsiregar LGTM but there is an issue after your previous changes.

screenshot from 2016-11-03 14-17-03

run `tempel` without parameter should return help.

**Comment by nsiregar** [comment]
@herpiko i've update tempel for
1. displaying help while error occured
2. no parameter changed, only param `-f` to `-s` as mentioned above

**Comment by herpiko** [comment]
@nsiregar Great!

But, this doesnt play well in limited env like no GUI. Since there is no copy/paste, it thrown error : 

```
deploy@ubuntu-1gb-sgp1-01:~/src/tempel-cli-py$ ./tempel 
Traceback (most recent call last):
  File "./tempel", line 76, in <module>
    get_args()
  File "./tempel", line 43, in get_args
    content = pyperclip.paste() #default source of tempel is string from clipboard
  File "/usr/local/lib/python2.7/dist-packages/pyperclip/clipboards.py", line 125, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.exceptions.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.org 
deploy@ubuntu-1gb-sgp1-01:~/src/tempel-cli-py$ 
```

Can you catch it?

**Comment by herpiko** [comment]
@nsiregar let move it to new issue (pyperclip) :)

@tuanpembual LGTM.

**Comment by herpiko** [comment]
@nsiregar @tuanpembual LGTM!

[LGTM](https://i.imgur.com/ZmlQh8H.gif)

**Pull request merged**
